// Code generated by protoc-gen-go. DO NOT EDIT.
// source: target.proto

package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Target struct {
	Access               int32    `protobuf:"varint,1,opt,name=access,proto3" json:"access,omitempty"`
	Remarks              string   `protobuf:"bytes,2,opt,name=remarks,proto3" json:"remarks,omitempty"`
	TransactionHash      string   `protobuf:"bytes,3,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Target) Reset()         { *m = Target{} }
func (m *Target) String() string { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()    {}
func (*Target) Descriptor() ([]byte, []int) {
	return fileDescriptor_target_35116cb8f9abc685, []int{0}
}
func (m *Target) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Target.Unmarshal(m, b)
}
func (m *Target) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Target.Marshal(b, m, deterministic)
}
func (dst *Target) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Target.Merge(dst, src)
}
func (m *Target) XXX_Size() int {
	return xxx_messageInfo_Target.Size(m)
}
func (m *Target) XXX_DiscardUnknown() {
	xxx_messageInfo_Target.DiscardUnknown(m)
}

var xxx_messageInfo_Target proto.InternalMessageInfo

func (m *Target) GetAccess() int32 {
	if m != nil {
		return m.Access
	}
	return 0
}

func (m *Target) GetRemarks() string {
	if m != nil {
		return m.Remarks
	}
	return ""
}

func (m *Target) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func init() {
	proto.RegisterType((*Target)(nil), "model.Target")
}

func init() { proto.RegisterFile("target.proto", fileDescriptor_target_35116cb8f9abc685) }

var fileDescriptor_target_35116cb8f9abc685 = []byte{
	// 119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x49, 0x2c, 0x4a,
	0x4f, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcd, 0x4f, 0x49, 0xcd, 0x51,
	0x4a, 0xe1, 0x62, 0x0b, 0x01, 0x0b, 0x0b, 0x89, 0x71, 0xb1, 0x25, 0x26, 0x27, 0xa7, 0x16, 0x17,
	0x4b, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x41, 0x79, 0x42, 0x12, 0x5c, 0xec, 0x45, 0xa9, 0xb9,
	0x89, 0x45, 0xd9, 0xc5, 0x12, 0x4c, 0x40, 0x09, 0xce, 0x20, 0x18, 0x57, 0x48, 0x83, 0x8b, 0xbf,
	0xa4, 0x28, 0x31, 0xaf, 0x38, 0x31, 0xb9, 0x24, 0x33, 0x3f, 0xcf, 0x23, 0xb1, 0x38, 0x43, 0x82,
	0x19, 0xac, 0x02, 0x5d, 0x38, 0x89, 0x0d, 0x6c, 0xa7, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xb9,
	0x3c, 0x77, 0xaa, 0x83, 0x00, 0x00, 0x00,
}
