[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "gopkg.in/fsnotify/fsnotify.v1"

[[override]]
  branch = "master"
  name = "github.com/hpcloud/tail"


[[constraint]]
  name = "github.com/hyperledger/fabric"
  version = "1.3.0"

[[override]]
  name = "github.com/docker/docker"
  branch = "master"

[[override]]
  name = "github.com/docker/libnetwork"
  branch = "master"
